services:
  db:
    image: ghcr.io/hugocruz13/neighbourshare-db:with_data
    container_name: sql_server
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=DEVesi2025
      - MSSQL_PID=Developer
    ports:
      - "1433:1433"
    networks:
      - app_network
    volumes:
      - sql_data:/var/opt/mssql

  backend:
    image: ghcr.io/hugocruz13/neighbourshare-backend:latest
    container_name: neighbourshare_backend
    environment:
      - DATABASE_URL=mssql+pyodbc://sa:DEVesi2025@db:1433/NeighbourShare?driver=ODBC+Driver+17+for+SQL+Server
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - app_network

  frontend:
    image: ghcr.io/hugocruz13/neighbourshare-frontend:latest
    container_name: neighbourshare_frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  sql_data:
